### PR TITLE
Update to 0.9

### PR DESCRIPTION
**Pull request by runiq**
- Also remove now-incorporated ARM fixes
- Remove superfluous appstream-compose invocation

### CODE REVIEW

**Comment by runiq** [comment]
Hitting https://github.com/brummer10/Ratatouille.lv2/issues/26, I'll see what I can do.

**Comment by hfiguiere** [comment]
0.9.1 is out, not sure it fixes it. It's fixable though.

**Comment by hfiguiere** [comment]
seems the build work with 0.9.1. See #2

**Comment by runiq** [comment]
Yeah, I'll close this PR and merge the other one. Sorry for the long silence, been sick for the last few weeks.

**Pull request closed without merging**
